
import java.text.NumberFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angela
 */
public class SignCalc extends javax.swing.JFrame {

    /**
     * Creates new form SignCalc
     */
    public SignCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupColor = new javax.swing.ButtonGroup();
        lbTitle = new javax.swing.JLabel();
        lbWords = new javax.swing.JLabel();
        lbWoodType = new javax.swing.JLabel();
        lbChar = new javax.swing.JLabel();
        lbNumber = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        txWords = new javax.swing.JTextField();
        ckOak = new javax.swing.JCheckBox();
        rbBlack = new javax.swing.JRadioButton();
        rbGold = new javax.swing.JRadioButton();
        txNumber = new javax.swing.JTextField();
        txTotal = new javax.swing.JTextField();
        btCalc = new javax.swing.JButton();
        btClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("ABC Sign Company");

        lbWords.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        lbWords.setText("Words on Sign");

        lbWoodType.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        lbWoodType.setText("Wood Type");

        lbChar.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        lbChar.setText("Character Color");

        lbNumber.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        lbNumber.setText("Number of Signs");

        lbTotal.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        lbTotal.setText("Total Cost");

        ckOak.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        ckOak.setText("Oak");

        btGroupColor.add(rbBlack);
        rbBlack.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        rbBlack.setSelected(true);
        rbBlack.setText("Black/White");
        rbBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlackActionPerformed(evt);
            }
        });

        btGroupColor.add(rbGold);
        rbGold.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        rbGold.setText("Gold Leaf");

        txNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotal.setEnabled(false);

        btCalc.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        btCalc.setText("Calculate");
        btCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcActionPerformed(evt);
            }
        });

        btClear.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbChar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(lbWoodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckOak)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(txNumber, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBlack)
                            .addComponent(btCalc))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btClear)
                            .addComponent(rbGold)))
                    .addComponent(txWords, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWords, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txWords, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWoodType)
                    .addComponent(ckOak))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbChar)
                    .addComponent(rbBlack)
                    .addComponent(rbGold))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumber)
                    .addComponent(txNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCalc)
                    .addComponent(btClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBlackActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // code to clear form
        txWords.setText(""); // set text fields to empty
        txNumber.setText("");
        txTotal.setText("");
        ckOak.setSelected(false);
        btGroupColor.clearSelection();
        rbBlack.setSelected(true);
    }//GEN-LAST:event_btClearActionPerformed

    private void btCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcActionPerformed
        // code to calculate cost of sign
        double totalCost = 30.00; // price accumulator -- every sign starts at 30
        
        // check if oak is selected
        if (ckOak.isSelected()) {
            totalCost += 15.00;
        }
        // check if gold is selected
        if (rbGold.isSelected()) {
            totalCost += 12.00;
        }
        // check if num of chars > 6
        String words = txWords.getText();
        if (words.length() > 6) {
            int extraChar = words.length() - 6; // get extra chars to charge for
            totalCost += (extraChar * 3); // every char after 6 is $3 extra
        }
        // get num signs
        int numSigns = Integer.parseInt(txNumber.getText()); // convert string to num
        totalCost *= numSigns;
        // display total cost
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        txTotal.setText(String.valueOf(currency.format(totalCost))); // convert num to string
                                                    // to put back in text box (totalCost + ""); // easy cheat way to convert 
    }//GEN-LAST:event_btCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalc;
    private javax.swing.JButton btClear;
    private javax.swing.ButtonGroup btGroupColor;
    private javax.swing.JCheckBox ckOak;
    private javax.swing.JLabel lbChar;
    private javax.swing.JLabel lbNumber;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbWoodType;
    private javax.swing.JLabel lbWords;
    private javax.swing.JRadioButton rbBlack;
    private javax.swing.JRadioButton rbGold;
    private javax.swing.JTextField txNumber;
    private javax.swing.JTextField txTotal;
    private javax.swing.JTextField txWords;
    // End of variables declaration//GEN-END:variables
}
